#List of slots to create or modify.
#See documentation for syntax: https://docs.illusivesoulworks.com/curios/configuration#slot-configuration
#
slots = ["id=curio;size=4", "id=back;size=2", "id=belt;size=2", "id=charm;size=4", "id=head;size=4", "id=hands;size=2", "id=necklace;size=2", "id=ring;size=4", "id=feet;size=2", "id=flight_ring;size=1", "id=spellbook;size=1"]

