// 木材
ServerEvents.tags('item', event => {
  event.add('vinery:dark_cherry_logs', ['vinery:dark_cherry_log', 'vinery:dark_cherry_wood', 'vinery:stripped_dark_cherry_log', 'vinery:stripped_dark_cherry_wood'])
  event.add('minecraft:cherry_logs', ['vinery:dark_cherry_log', 'vinery:dark_cherry_wood'])
  event.add('minecraft:oak_logs', ['atmospheric:laurel_log', 'atmospheric:laurel_wood', 'bloomingnature:chestnut_log', 'bloomingnature:chestnut_wood', 'bloomingnature:swamp_oak_log', 'bloomingnature:swamp_oak_wood', 'natures_spirit:ghaf_log', 'natures_spirit:ghaf_wood', 'natures_spirit:olive_log', 'natures_spirit:olive_wood', 'natures_spirit:saxaul_log', 'natures_spirit:saxaul_wood', 'vinery:apple_log', 'vinery:apple_wood'])
  event.add('minecraft:spruce_logs', ['autumnity:maple_log', 'autumnity:maple_wood', 'biomemakeover:swamp_cypress_log', 'biomemakeover:swamp_cypress_wood', 'bloomingnature:fir_log', 'bloomingnature:fir_wood', 'bloomingnature:larch_log', 'bloomingnature:larch_wood', 'natures_spirit:cedar_log', 'natures_spirit:cedar_wood', 'natures_spirit:cypress_log', 'natures_spirit:cypress_wood', 'natures_spirit:fir_log', 'natures_spirit:fir_wood', 'natures_spirit:larch_log', 'natures_spirit:larch_wood', 'natures_spirit:maple_log', 'natures_spirit:maple_wood', 'natures_spirit:redwood_log', 'natures_spirit:redwood_wood', 'natures_spirit:sugi_log', 'natures_spirit:sugi_wood', 'upgrade_aquatic:river_log', 'upgrade_aquatic:river_wood'])
  event.add('minecraft:birch_logs', ['atmospheric:aspen_log', 'atmospheric:aspen_wood', 'biomemakeover:blighted_balsa_log', 'biomemakeover:blighted_balsa_wood', 'bloomingnature:aspen_log', 'bloomingnature:aspen_wood', 'natures_spirit:aspen_log', 'natures_spirit:aspen_wood', 'natures_spirit:wisteria_log', 'natures_spirit:wisteria_wood', 'quark:ancient_log', 'quark:ancient_wood'])
  event.add('minecraft:jungle_logs', ['atmospheric:morado_log', 'atmospheric:morado_wood', 'atmospheric:rosewood_log', 'atmospheric:yucca_log', 'atmospheric:yucca_wood', 'beachparty:palm_log', 'beachparty:palm_wood', 'bloomingnature:baobab_log', 'bloomingnature:baobab_wood', 'bloomingnature:fan_palm_log', 'bloomingnature:fan_palm_wood', 'natures_spirit:coconut_log', 'natures_spirit:coconut_wood', 'natures_spirit:palo_verde_log', 'natures_spirit:palo_verde_wood', 'quark:blossom_log', 'quark:blossom_wood'])
  event.add('minecraft:dark_oak_logs', ['atmospheric:grimwood_log', 'biomemakeover:ancient_oak_log', 'biomemakeover:ancient_oak_wood', 'bloomingnature:ebony_log', 'bloomingnature:ebony_wood', 'natures_spirit:joshua_bundle', 'natures_spirit:joshua_log', 'natures_spirit:stripped_joshua_bundle', 'natures_spirit:stripped_joshua_log', 'upgrade_aquatic:driftwood_log'])
  event.add('minecraft:mangrove_logs', ['bloomingnature:swamp_cypress_log', 'bloomingnature:swamp_cypress_wood', 'natures_spirit:willow_log', 'natures_spirit:willow_wood', 'quark:azalea_log', 'quark:azalea_wood'])
  event.add('create:modded_stripped_logs', ['atmospheric:stripped_laurel_log', 'autumnity:sappy_maple_log', 'autumnity:stripped_maple_log', 'caverns_and_chasms:stripped_azalea_log', 'endergetic:stripped_poise_stem', 'immortalers_delight:stripped_ancient_wood_log', 'immortalers_delight:stripped_himekaido_log', 'sakura:stripped_maple_log', 'sakura:stripped_sakura_log', 'upgrade_aquatic:stripped_driftwood_log', 'upgrade_aquatic:stripped_river_log'])
  event.add('create:modded_stripped_wood', ['atmospheric:stripped_laurel_wood', 'autumnity:sappy_maple_wood', 'autumnity:stripped_maple_wood', 'caverns_and_chasms:stripped_azalea_wood', 'endergetic:stripped_poise_wood', 'immortalers_delight:stripped_ancient_wood', 'immortalers_delight:stripped_himekaido_wood', 'sakura:stripped_maple_wood', 'sakura:stripped_sakura_wood', 'upgrade_aquatic:stripped_driftwood', 'upgrade_aquatic:stripped_river_wood'])
})

ServerEvents.tags('block', event => {
  event.add('vinery:dark_cherry_logs', ['vinery:dark_cherry_log', 'vinery:dark_cherry_wood', 'vinery:stripped_dark_cherry_log', 'vinery:stripped_dark_cherry_wood'])
})

// 蘑菇
ServerEvents.tags('item', event => {
  event.add('c:mushrooms', ['biomemakeover:green_glowshroom', 'biomemakeover:orange_glowshroom', 'biomemakeover:purple_glowshroom', 'natures_spirit:shiitake_mushroom', 'quark:glow_shroom', 'spelunkery:button_mushroom', 'spelunkery:crimini', 'spelunkery:portabella', 'tofucraft:zundatofu_mushroom'])
  event.add('forge:mushrooms', ['biomemakeover:green_glowshroom', 'biomemakeover:orange_glowshroom', 'biomemakeover:purple_glowshroom', 'natures_spirit:shiitake_mushroom', 'quark:glow_shroom', 'spelunkery:button_mushroom', 'spelunkery:crimini', 'spelunkery:portabella', 'tofucraft:zundatofu_mushroom'])
  event.add('pizzacraft:fermenting_items', ['spelunkery:button_mushroom', 'spelunkery:crimini', 'spelunkery:portabella'])
  event.add('farmersdelight:cabbage_roll_ingredients', ['spelunkery:button_mushroom', 'spelunkery:crimini', 'spelunkery:portabella'])
})

// 建筑方块
ServerEvents.tags('item', event => {
  event.add('forge:sandstone', ['natures_spirit:pink_sandstone'])
})

// 热源
ServerEvents.tags('block', event => {
  event.add('caverns_and_chasms:braziers', ['rubinated_nether:ruby_brazier'])
  event.add('minecraft:campfires', ['#caverns_and_chasms:braziers', 'supplementaries:fire_pit'])
  event.add('farmersdelight:heat_sources', ['#caverns_and_chasms:braziers', 'supplementaries:fire_pit'])
  event.add('farmersdelight:tray_heat_sources', ['#caverns_and_chasms:braziers', 'supplementaries:fire_pit'])
  event.add('create:passive_boiler_heaters', ['#caverns_and_chasms:braziers', 'supplementaries:fire_pit'])
  event.add('amendments:cauldron_heat_source', ['#caverns_and_chasms:braziers', 'supplementaries:fire_pit'])
  event.add('create:fan_heaters', ['#caverns_and_chasms:braziers', 'supplementaries:fire_pit'])
  event.add('mynethersdelight:letios_flames', ['#caverns_and_chasms:braziers', 'supplementaries:fire_pit'])
  event.add('forge:allows_cooking', ['#caverns_and_chasms:braziers', 'supplementaries:fire_pit'])
  event.add('candlelight:allows_cooking', ['#caverns_and_chasms:braziers', 'supplementaries:fire_pit'])
  event.add('farm_and_charm:allows_cooking', ['#caverns_and_chasms:braziers', 'supplementaries:fire_pit'])
})

// 肉类
ServerEvents.tags('item', event => {
  event.add('forge:raw_vension', ['delightful:venison_chops'])
  event.add('c:raw_meat', ['delightful:raw_goat', 'delightful:venison_chops', 'immortalers_delight:raw_sniffer_steak', 'mynethersdelight:hoglin_loin', 'netherexp:hogham'])
  event.add('forge:raw_meat', ['delightful:raw_goat', 'delightful:venison_chops', 'immortalers_delight:raw_sniffer_steak', 'mynethersdelight:hoglin_loin', 'netherexp:hogham'])
  event.add('forge:raw_meats', ['delightful:raw_goat', 'delightful:venison_chops', 'immortalers_delight:raw_sniffer_steak', 'mynethersdelight:hoglin_loin', 'netherexp:hogham'])
  event.add('forge:meats', ['delightful:cooked_goat', 'delightful:cooked_venison_chops', 'delightful:raw_goat', 'delightful:venison_chops', 'immortalers_delight:cooked_sniffer_steak', 'immortalers_delight:raw_sniffer_steak', 'mynethersdelight:cooked_loin', 'mynethersdelight:hoglin_loin', 'netherexp:cooked_hogham', 'netherexp:hogham'])
  event.add('forge:rawmeats', ['delightful:raw_goat', 'delightful:venison_chops', 'immortalers_delight:raw_sniffer_steak', 'mynethersdelight:hoglin_loin', 'netherexp:hogham'])
  event.add('forge:cooked_vension', ['delightful:cooked_venison_chops'])
  event.add('c:cooked_meat', ['delightful:cooked_goat', 'delightful:cooked_venison_chops', 'immortalers_delight:cooked_sniffer_steak', 'mynethersdelight:cooked_loin', 'netherexp:cooked_hogham'])
  event.add('forge:cooked_meat', ['delightful:cooked_goat', 'delightful:cooked_venison_chops', 'immortalers_delight:cooked_sniffer_steak', 'mynethersdelight:cooked_loin', 'netherexp:cooked_hogham'])
  event.add('forge:cooked_meats', ['delightful:cooked_goat', 'delightful:cooked_venison_chops', 'immortalers_delight:cooked_sniffer_steak', 'mynethersdelight:cooked_loin', 'netherexp:cooked_hogham'])
  event.add('forge:cookedmeats', ['delightful:cooked_goat', 'delightful:cooked_venison_chops', 'immortalers_delight:cooked_sniffer_steak', 'mynethersdelight:cooked_loin', 'netherexp:cooked_hogham'])
  event.add('forge:raw_pork', ['mynethersdelight:hoglin_loin', 'netherexp:hogham'])
  event.add('forge:cooked_pork', ['mynethersdelight:cooked_loin', 'netherexp:cooked_hogham'])
  event.add('forge:raw_mutton', ['delightful:raw_goat'])
  event.add('forge:cooked_mutton', ['delightful:cooked_goat'])
  event.add('farmersdelight:cabbage_roll_ingredients', ['delightful:cooked_venison_chops', 'delightful:venison_chops', 'mynethersdelight:cooked_loin', 'mynethersdelight:hoglin_loin'])
})

// 水果
ServerEvents.tags('item', event => {
  event.add('forge:fruits', ['atmospheric:blood_orange', 'atmospheric:yucca_fruit', 'beachparty:coconut_open', 'delightful:salmonberries', 'farm_and_charm:strawberry', 'fruitsdelight:blueberry', 'fruitsdelight:cranberry', 'fruitsdelight:durian_flesh', 'fruitsdelight:hamimelon_slice', 'fruitsdelight:hawberry', 'fruitsdelight:lemon', 'fruitsdelight:lemon_slice', 'fruitsdelight:lychee', 'fruitsdelight:mango', 'fruitsdelight:orange', 'fruitsdelight:peach', 'fruitsdelight:pear', 'fruitsdelight:persimmon', 'fruitsdelight:pineapple', 'immortalers_delight:himekaido', 'minecraft:apple', 'minecraft:glow_berries', 'minecraft:melon_slice', 'minecraft:sweet_berries', 'natures_spirit:coconut_half', 'natures_spirit:olives', 'tofucraft:apricot', 'vinery:jungle_grapes_red', 'vinery:jungle_grapes_white', 'vinery:red_grape', 'vinery:savanna_grapes_red', 'vinery:taiga_grapes_red', 'vinery:taiga_grapes_white', 'vinery:white_grape', 'youkaishomecoming:black_grape', 'youkaishomecoming:red_grape', 'youkaishomecoming:white_grape'])
  event.add('forge:crops', ['atmospheric:blood_orange', 'atmospheric:currant', 'atmospheric:dragon_fruit', 'atmospheric:orange', 'atmospheric:passion_fruit', 'atmospheric:yucca_fruit', 'beachparty:coconut_open', 'delightful:cantaloupe_slice', 'delightful:salmonberries', 'farm_and_charm:strawberry', 'fruitsdelight:blueberry', 'fruitsdelight:cranberry', 'fruitsdelight:hamimelon_slice', 'fruitsdelight:hawberry', 'fruitsdelight:lemon', 'fruitsdelight:lychee', 'fruitsdelight:mango', 'fruitsdelight:orange', 'fruitsdelight:peach', 'fruitsdelight:pear', 'fruitsdelight:persimmon', 'fruitsdelight:pineapple', 'immortalers_delight:himekaido', 'minecraft:apple', 'minecraft:glow_berries', 'minecraft:melon_slice', 'minecraft:sweet_berries', 'natures_spirit:coconut_half', 'natures_spirit:olives', 'tofucraft:apricot', 'trailandtales_delight:lantern_fruit', 'vinery:jungle_grapes_red', 'vinery:jungle_grapes_white', 'vinery:red_grape', 'vinery:savanna_grapes_red', 'vinery:taiga_grapes_red', 'vinery:taiga_grapes_white', 'vinery:white_grape', 'youkaishomecoming:black_grape', 'youkaishomecoming:red_grape', 'youkaishomecoming:white_grape'])
  event.add('forge:berries', ['atmospheric:currant', 'delightful:salmonberries', 'farm_and_charm:strawberry', 'fruitsdelight:blueberry', 'fruitsdelight:cranberry', 'immortalers_delight:himekaido', 'minecraft:glow_berries', 'minecraft:sweet_berries', 'vinery:jungle_grapes_red', 'vinery:jungle_grapes_white', 'vinery:red_grape', 'vinery:savanna_grapes_red', 'vinery:taiga_grapes_red', 'vinery:taiga_grapes_white', 'vinery:white_grape', 'youkaishomecoming:black_grape', 'youkaishomecoming:red_grape', 'youkaishomecoming:white_grape'])
  event.add('forge:fruits/apricot', ['tofucraft:apricot'])
  event.add('forge:crops/apricot', ['tofucraft:apricot'])
  event.add('forge:crops/salmonberries', ['delightful:salmonberries'])
  event.add('forge:fruits/salmonberries', ['delightful:salmonberries'])
  event.add('forge:berries/salmonberries', ['delightful:salmonberries'])
  event.add('forge:crops/raspberry', ['delightful:salmonberries'])
  event.add('forge:fruits/raspberry', ['delightful:salmonberries'])
  event.add('forge:berries/raspberry', ['delightful:salmonberries'])
  event.add('forge:crops/raspberries', ['delightful:salmonberries'])
  event.add('forge:fruits/raspberries', ['delightful:salmonberries'])
  event.add('forge:berries/raspberries', ['delightful:salmonberries'])
  event.add('forge:crops/strawberries', ['farm_and_charm:strawberry'])
  event.add('forge:crops/strawberry', ['farm_and_charm:strawberry'])
  event.add('forge:fruits/strawberries', ['farm_and_charm:strawberry'])
  event.add('forge:fruits/strawberry', ['farm_and_charm:strawberry'])
  event.add('forge:berries/strawberries', ['farm_and_charm:strawberry'])
  event.add('forge:berries/strawberry', ['farm_and_charm:strawberry'])
  event.add('forge:crops/blueberry', ['fruitsdelight:blueberry'])
  event.add('forge:crops/blueberries', ['fruitsdelight:blueberry'])
  event.add('forge:fruits/blueberry', ['fruitsdelight:blueberry'])
  event.add('forge:fruits/blueberries', ['fruitsdelight:blueberry'])
  event.add('forge:berries/blueberry', ['fruitsdelight:blueberry'])
  event.add('forge:berries/blueberries', ['fruitsdelight:blueberry'])
  event.add('forge:crops/coconut', ['beachparty:coconut_open', 'natures_spirit:coconut_half'])
  event.add('forge:fruits/coconut', ['beachparty:coconut_open', 'natures_spirit:coconut_half'])
  event.add('forge:coconut', ['beachparty:coconut_open', 'natures_spirit:coconut_half'])
  event.add('natures_spirit:coconut_items', ['beachparty:coconut_open'])
  event.add('forge:crops/hawthorn', ['fruitsdelight:hawberry'])
  event.add('forge:fruits/hawthorn', ['fruitsdelight:hawberry'])
  event.add('forge:crops/hawberry', ['fruitsdelight:hawberry'])
  event.add('forge:fruits/hawberry', ['fruitsdelight:hawberry'])
  event.add('forge:crops/lychee', ['fruitsdelight:lychee'])
  event.add('forge:fruits/lychee', ['fruitsdelight:lychee'])
  event.add('forge:crops/litchi', ['fruitsdelight:lychee'])
  event.add('forge:fruits/litchi', ['fruitsdelight:lychee'])
  event.add('forge:crops/persimmon', ['fruitsdelight:persimmon'])
  event.add('forge:fruits/persimmon', ['fruitsdelight:persimmon'])
  event.add('forge:crops/mango', ['fruitsdelight:mango'])
  event.add('forge:fruits/mango', ['fruitsdelight:mango'])
  event.add('forge:crops/pear', ['fruitsdelight:pear'])
  event.add('forge:fruits/pear', ['fruitsdelight:pear'])
  event.add('forge:crops/peach', ['fruitsdelight:peach'])
  event.add('forge:fruits/peach', ['fruitsdelight:peach'])
  event.add('forge:crops/lemon', ['fruitsdelight:lemon'])
  event.add('forge:fruits/lemon', ['fruitsdelight:lemon'])
  event.add('forge:crops/orange', ['atmospheric:blood_orange', 'atmospheric:orange', 'fruitsdelight:orange'])
  event.add('forge:fruits/orange', ['atmospheric:blood_orange', 'fruitsdelight:orange'])
  event.add('forge:crops/hamimelon', ['delightful:cantaloupe_slice', 'fruitsdelight:hamimelon_slice'])
  event.add('forge:fruits/hamimelon', ['fruitsdelight:hamimelon_slice'])
  event.add('forge:crops/pineapple', ['fruitsdelight:pineapple'])
  event.add('forge:fruits/pineapple', ['fruitsdelight:pineapple'])
  event.add('forge:crops/cherry', ['vinery:cherry'])
  event.add('forge:fruits/cherry', ['vinery:cherry'])
  event.add('forge:crops/cherries', ['vinery:cherry'])
  event.add('forge:fruits/cherries', ['vinery:cherry'])
  event.add('forge:crops/cranberry', ['fruitsdelight:cranberry'])
  event.add('forge:fruits/cranberry', ['fruitsdelight:cranberry'])
  event.add('forge:berries/cranberry', ['fruitsdelight:cranberry'])
  event.add('forge:crops/grape', ['vinery:jungle_grapes_red', 'vinery:jungle_grapes_white', 'vinery:red_grape', 'vinery:savanna_grapes_red', 'vinery:taiga_grapes_red', 'vinery:taiga_grapes_white', 'vinery:white_grape', 'youkaishomecoming:black_grape', 'youkaishomecoming:red_grape', 'youkaishomecoming:white_grape'])
  event.add('forge:fruits/grape', ['vinery:jungle_grapes_red', 'vinery:jungle_grapes_white', 'vinery:red_grape', 'vinery:savanna_grapes_red', 'vinery:taiga_grapes_red', 'vinery:taiga_grapes_white', 'vinery:white_grape', 'youkaishomecoming:black_grape', 'youkaishomecoming:red_grape', 'youkaishomecoming:white_grape'])
  event.add('forge:berries/grape', ['vinery:jungle_grapes_red', 'vinery:jungle_grapes_white', 'vinery:red_grape', 'vinery:savanna_grapes_red', 'vinery:taiga_grapes_red', 'vinery:taiga_grapes_white', 'vinery:white_grape', 'youkaishomecoming:black_grape', 'youkaishomecoming:red_grape', 'youkaishomecoming:white_grape'])
  event.add('forge:crops/grapes', ['vinery:jungle_grapes_red', 'vinery:jungle_grapes_white', 'vinery:red_grape', 'vinery:savanna_grapes_red', 'vinery:taiga_grapes_red', 'vinery:taiga_grapes_white', 'vinery:white_grape', 'youkaishomecoming:black_grape', 'youkaishomecoming:red_grape', 'youkaishomecoming:white_grape'])
  event.add('forge:fruits/grapes', ['vinery:jungle_grapes_red', 'vinery:jungle_grapes_white', 'vinery:red_grape', 'vinery:savanna_grapes_red', 'vinery:taiga_grapes_red', 'vinery:taiga_grapes_white', 'vinery:white_grape', 'youkaishomecoming:black_grape', 'youkaishomecoming:red_grape', 'youkaishomecoming:white_grape'])
  event.add('forge:berries/grapes', ['vinery:jungle_grapes_red', 'vinery:jungle_grapes_white', 'vinery:red_grape', 'vinery:savanna_grapes_red', 'vinery:taiga_grapes_red', 'vinery:taiga_grapes_white', 'vinery:white_grape', 'youkaishomecoming:black_grape', 'youkaishomecoming:red_grape', 'youkaishomecoming:white_grape'])
  event.add('vinery:red_grape', ['youkaishomecoming:black_grape', 'youkaishomecoming:red_grape'])
  event.add('vinery:grape', ['youkaishomecoming:black_grape', 'youkaishomecoming:red_grape', 'youkaishomecoming:white_grape'])
  event.add('vinery:white_grape', ['youkaishomecoming:white_grape'])
  event.add('forge:crops/cantaloupe', ['delightful:cantaloupe_slice'])
  event.add('forge:crops/apple', ['minecraft:apple'])
  event.add('forge:fruits/apple', ['minecraft:apple'])
  event.add('forge:crops/watermelon', ['minecraft:melon_slice'])
  event.add('forge:fruits/watermelon', ['minecraft:melon_slice'])
  event.add('forge:crops/melon', ['minecraft:melon_slice'])
  event.add('forge:fruits/melon', ['minecraft:melon_slice'])
  event.add('forge:crops/sweet_berries', ['minecraft:sweet_berries'])
  event.add('forge:fruits/sweet_berries', ['minecraft:sweet_berries'])
  event.add('forge:berries/sweet_berries', ['minecraft:sweet_berries'])
  event.add('forge:crops/glow_berries', ['minecraft:glow_berries'])
  event.add('forge:fruits/glow_berries', ['minecraft:glow_berries'])
  event.add('forge:berries/glow_berries', ['minecraft:glow_berries'])
  event.add('forge:crops/currant', ['atmospheric:currant'])
  event.add('forge:berries/currant', ['atmospheric:currant'])
  event.add('forge:crops/yucca', ['atmospheric:yucca_fruit'])
  event.add('forge:fruits/yucca', ['atmospheric:yucca_fruit'])
  event.add('forge:crops/dragon_fruit', ['atmospheric:dragon_fruit'])
  event.add('forge:crops/citrus', ['atmospheric:blood_orange', 'atmospheric:orange'])
  event.add('forge:crops/passion_fruit', ['atmospheric:passion_fruit'])
  event.add('forge:crops/passionfruit', ['atmospheric:passion_fruit'])
  event.add('forge:fruits/citrus', ['atmospheric:blood_orange'])
  event.add('forge:crops/olives', ['natures_spirit:olives'])
  event.add('forge:crops/olive', ['natures_spirit:olives'])
  event.add('forge:fruits/olives', ['natures_spirit:olives'])
  event.add('forge:fruits/olive', ['natures_spirit:olives'])
  event.add('forge:fruits/durian', ['fruitsdelight:durian_flesh'])
})

// 蔬菜
ServerEvents.tags('item', event => {
  event.add('forge:crops', ['atmospheric:aloe_leaves', 'bakeries:tomato', 'biomemakeover:bulbus_root', 'delightful:cactus_flesh', 'farm_and_charm:barley', 'farm_and_charm:corn', 'farm_and_charm:lettuce', 'farm_and_charm:oat', 'farm_and_charm:onion', 'farm_and_charm:tomato', 'immortalers_delight:evolutcorn', 'mynethersdelight:bullet_pepper', 'natures_spirit:desert_turnip', 'neapolitan:mint_leaves', 'netherexp:cerebrage', 'spelunkery:eggplant', 'tofucraft:chili', 'tofucraft:leek', 'trailandtales_delight:pitcher_taro', 'vintagedelight:cucumber', 'vintagedelight:ghost_pepper', 'youkaishomecoming:cucumber'])
  event.add('forge:vegetables', ['atmospheric:aloe_leaves', 'bakeries:tomato', 'biomemakeover:bulbus_root', 'delightful:cactus_flesh', 'farm_and_charm:lettuce', 'farm_and_charm:onion', 'farm_and_charm:tomato', 'immortalers_delight:evolutcorn', 'immortalers_delight:evolutcorn_grains', 'mynethersdelight:bullet_pepper', 'natures_spirit:desert_turnip', 'neapolitan:mint_leaves', 'netherexp:cerebrage', 'spelunkery:eggplant', 'tofucraft:chili', 'tofucraft:leek', 'trailandtales_delight:pitcher_taro', 'vintagedelight:cucumber', 'vintagedelight:ghost_pepper', 'youkaishomecoming:cucumber'])
  event.add('forge:crops/tomato', ['bakeries:tomato', 'farm_and_charm:tomato'])
  event.add('forge:vegetables/tomato', ['bakeries:tomato', 'farm_and_charm:tomato'])
  event.add('forge:crops/oat', ['farm_and_charm:oat'])
  event.add('forge:grain', ['farm_and_charm:barley', 'farm_and_charm:corn', 'farm_and_charm:oat', 'immortalers_delight:evolutcorn', 'immortalers_delight:evolutcorn_grains'])
  event.add('forge:grain/oat', ['farm_and_charm:oat'])
  event.add('forge:crops/cabbage', ['farm_and_charm:lettuce', 'netherexp:cerebrage'])
  event.add('forge:vegetables/cabbage', ['farm_and_charm:lettuce', 'netherexp:cerebrage'])
  event.add('forge:crops/corn', ['farm_and_charm:corn', 'immortalers_delight:evolutcorn'])
  event.add('forge:grain/corn', ['farm_and_charm:corn', 'immortalers_delight:evolutcorn', 'immortalers_delight:evolutcorn_grains'])
  event.add('forge:crops/barley', ['farm_and_charm:barley'])
  event.add('forge:grain/barley', ['farm_and_charm:barley'])
  event.add('forge:crops/turnip', ['natures_spirit:desert_turnip'])
  event.add('forge:vegetables/turnip', ['natures_spirit:desert_turnip'])
  event.add('forge:crops/pepper', ['mynethersdelight:bullet_pepper', 'tofucraft:chili', 'vintagedelight:ghost_pepper'])
  event.add('forge:vegetables/pepper', ['mynethersdelight:bullet_pepper', 'tofucraft:chili', 'vintagedelight:ghost_pepper'])
  event.add('forge:pepper', ['mynethersdelight:bullet_pepper', 'vintagedelight:ghost_pepper'])
  event.add('forge:crops/chilipepper', ['mynethersdelight:bullet_pepper', 'tofucraft:chili', 'vintagedelight:ghost_pepper'])
  event.add('forge:vegetables/chilipepper', ['mynethersdelight:bullet_pepper', 'tofucraft:chili', 'vintagedelight:ghost_pepper'])
  event.add('forge:crops/chili_pepper', ['mynethersdelight:bullet_pepper', 'tofucraft:chili', 'vintagedelight:ghost_pepper'])
  event.add('forge:vegetables/chili_pepper', ['mynethersdelight:bullet_pepper', 'tofucraft:chili', 'vintagedelight:ghost_pepper'])
  event.add('forge:chilipepper', ['crockpot:pepper', 'mynethersdelight:bullet_pepper', 'vintagedelight:ghost_pepper'])
  event.add('forge:vegetables/chili', ['tofucraft:chili'])
  event.add('forge:crops/chili', ['tofucraft:chili'])
  event.add('forge:vegetables/leek', ['tofucraft:leek'])
  event.add('forge:crops/leek', ['tofucraft:leek'])
  event.add('forge:crops/cucumber', ['vintagedelight:cucumber', 'youkaishomecoming:cucumber'])
  event.add('forge:vegetables/cucumber', ['vintagedelight:cucumber', 'youkaishomecoming:cucumber'])
  event.add('forge:crops/onion', ['farm_and_charm:onion'])
  event.add('forge:vegetables/onion', ['farm_and_charm:onion'])
  event.add('forge:vegetables/corn', ['immortalers_delight:evolutcorn', 'immortalers_delight:evolutcorn_grains'])
  event.add('forge:seeds', ['immortalers_delight:evolutcorn_grains'])
  event.add('forge:seeds/corn', ['immortalers_delight:evolutcorn_grains'])
  event.add('forge:crops/aloe', ['atmospheric:aloe_leaves'])
  event.add('forge:vegetables/aloe', ['atmospheric:aloe_leaves'])
  event.add('forge:crops/mint', ['neapolitan:mint_leaves'])
  event.add('forge:vegetables/mint', ['neapolitan:mint_leaves'])
  event.add('farm_and_charm:tomato', ['farmersdelight:tomato'])
  event.add('c:tomato', ['farmersdelight:tomato'])
  event.add('c:cabbage', ['farmersdelight:cabbage'])
  event.add('farm_and_charm:cabbage', ['farmersdelight:cabbage'])
  event.add('forge:crops/eggplant', ['spelunkery:eggplant'])
  event.add('forge:vegetables/eggplant', ['spelunkery:eggplant'])
  event.add('forge:crops/ginger', ['biomemakeover:bulbus_root'])
  event.add('forge:vegetables/ginger', ['biomemakeover:bulbus_root'])
  event.add('c:crops/tomato', ['farmersdelight:tomato'])
  event.add('c:crops/cabbage', ['farmersdelight:cabbage'])
})

// 种子
ServerEvents.tags('item', event => {
  event.add('forge:seeds/tomato', ['farm_and_charm:tomato_seeds'])
  event.add('forge:seeds/cabbage', ['farm_and_charm:lettuce_seeds'])
  event.add('forge:seeds/oat', ['farm_and_charm:oat_seeds', 'vintagedelight:oat_seeds'])
  event.add('forge:seeds/pepper', ['vintagedelight:ghost_pepper_seeds'])
  event.add('forge:seeds/chilipepper', ['vintagedelight:ghost_pepper_seeds'])
  event.add('forge:seeds/cantaloupe', ['fruitsdelight:hamimelon_seeds'])
  event.add('forge:seeds/hamimelon', ['delightful:cantaloupe_seeds', 'fruitsdelight:hamimelon_seeds'])
  event.add('forge:seeds/strawberry', ['farm_and_charm:strawberry_seeds'])
})

// 坚果和谷物
ServerEvents.tags('item', event => {
  event.add('forge:crops', ['immortalers_delight:kwat_wheat', 'neapolitan:adzuki_beans', 'vintagedelight:oat', 'vintagedelight:peanut', 'youkaishomecoming:redbean'])
  event.add('forge:crops/nut', ['vintagedelight:peanut'])
  event.add('forge:crops/peanut', ['vintagedelight:peanut'])
  event.add('forge:nut', ['vintagedelight:peanut'])
  event.add('forge:nuts', ['vintagedelight:peanut'])
  event.add('forge:nut/peanut', ['vintagedelight:peanut'])
  event.add('forge:nuts/peanut', ['vintagedelight:peanut'])
  event.add('forge:crops/oat', ['vintagedelight:oat'])
  event.add('forge:grain', ['immortalers_delight:kwat_wheat', 'vintagedelight:oat'])
  event.add('forge:grain/oat', ['vintagedelight:oat'])
  event.add('forge:crops/wheat', ['immortalers_delight:kwat_wheat', 'vintagedelight:oat'])
  event.add('forge:grain/wheat', ['immortalers_delight:kwat_wheat', 'vintagedelight:oat'])
  event.add('c:wheat', ['immortalers_delight:kwat_wheat', 'vintagedelight:oat'])
  event.add('farm_and_charm:wheat', ['immortalers_delight:kwat_wheat', 'vintagedelight:oat'])
  event.add('meadow:wheat', ['immortalers_delight:kwat_wheat', 'vintagedelight:oat'])
  event.add('forge:crops/barley', ['immortalers_delight:kwat_wheat'])
  event.add('forge:grain/barley', ['immortalers_delight:kwat_wheat'])
  event.add('farm_and_charm:mushrooms', ['spelunkery:button_mushroom', 'spelunkery:crimini', 'spelunkery:portabella'])
  event.add('forge:crops/adzuki', ['neapolitan:adzuki_beans', 'youkaishomecoming:redbean'])
  event.add('forge:seeds', ['neapolitan:adzuki_beans', 'youkaishomecoming:redbean'])
  event.add('forge:seeds/adzuki', ['neapolitan:adzuki_beans', 'youkaishomecoming:redbean'])
})

// 水产
ServerEvents.tags('item', event => {
  event.add('forge:crab_meat', ['biomemakeover:raw_crab', 'quark:crab_leg'])
  event.add('minecraft:fishes', ['youkaishomecoming:raw_lamprey_fillet', 'youkaishomecoming:roasted_lamprey_fillet'])
  event.add('forge:raw_fishes', ['youkaishomecoming:raw_lamprey_fillet'])
  event.add('c:raw_fish', ['youkaishomecoming:raw_lamprey_fillet'])
  event.add('forge:meats', ['youkaishomecoming:raw_lamprey_fillet', 'youkaishomecoming:roasted_lamprey_fillet'])
  event.add('minecraft:is_meat', ['youkaishomecoming:raw_lamprey_fillet', 'youkaishomecoming:roasted_lamprey_fillet'])
  event.add('forge:cooked_fishes', ['youkaishomecoming:roasted_lamprey_fillet'])
  event.add('c:cooked_fish', ['youkaishomecoming:roasted_lamprey_fillet'])
})

// 巧克力
ServerEvents.tags('item', event => {
  event.add('forge:bars/chocolate', ['#c:chocolate', '#forge:chocolate'])
  event.add('forge:chocolate', ['#forge:bars/chocolate'])
  event.add('c:chocolate', ['#forge:chocolate'])
  event.add('farm_and_charm:chocolate', ['#forge:chocolate'])
})

// 切片
ServerEvents.tags('item', event => {
  event.add('forge:fruits', ['fruitsdelight:pineapple_slice'])
})

// 工具
ServerEvents.tags('item', event => {
  event.add('farmersdelight:tools/knives', ['#forge:tools/knives'])
  event.add('farmersdelight:straw_harvesters', ['#forge:tools/knives'])
  event.add('forge:tools/rollingpin', ['tofucraft:rollingpin'])
  event.add('forge:tools/rolling_pin', ['tofucraft:rollingpin'])
  event.add('bakeries:bread_knife', ['#forge:tools/knives'])
  event.add('minecraft:hoes', ['create_sa:brass_hoe', 'create_sa:copper_hoe', 'create_sa:zinc_hoe', 'tofucraft:tofu_diamond_hoe', 'tofucraft:tofu_kinu_hoe', 'tofucraft:tofu_metal_hoe', 'tofucraft:tofu_momen_hoe', 'tofucraft:tofu_solid_hoe'])
  event.add('minecraft:tools', ['caverns_and_chasms:tuning_fork', 'create_sa:blazing_axe', 'create_sa:blazing_cleaver', 'create_sa:blazing_pickaxe', 'create_sa:blazing_shovel', 'create_sa:brass_axe', 'create_sa:brass_hoe', 'create_sa:brass_pickaxe', 'create_sa:brass_shovel', 'create_sa:brass_sword', 'create_sa:copper_axe', 'create_sa:copper_hoe', 'create_sa:copper_pickaxe', 'create_sa:copper_shovel', 'create_sa:copper_sword', 'create_sa:experience_axe', 'create_sa:experience_pickaxe', 'create_sa:experience_shovel', 'create_sa:experience_sword', 'create_sa:rose_quartz_axe', 'create_sa:rose_quartz_pickaxe', 'create_sa:rose_quartz_shovel', 'create_sa:rose_quartz_sword', 'create_sa:zinc_axe', 'create_sa:zinc_hoe', 'create_sa:zinc_pickaxe', 'create_sa:zinc_shovel', 'create_sa:zinc_sword', 'tofucraft:rollingpin', 'tofucraft:tofu_diamond_hoe', 'tofucraft:tofu_kinu_hoe', 'tofucraft:tofu_metal_hoe', 'tofucraft:tofu_momen_hoe', 'tofucraft:tofu_solid_hoe'])
  event.add('minecraft:shovels', ['create_sa:blazing_shovel', 'create_sa:brass_shovel', 'create_sa:copper_shovel', 'create_sa:experience_shovel', 'create_sa:rose_quartz_shovel', 'create_sa:zinc_shovel'])
  event.add('minecraft:axes', ['create_sa:blazing_axe', 'create_sa:brass_axe', 'create_sa:copper_axe', 'create_sa:experience_axe', 'create_sa:rose_quartz_axe', 'create_sa:zinc_axe'])
  event.add('minecraft:pickaxes', ['create_sa:blazing_pickaxe', 'create_sa:brass_pickaxe', 'create_sa:copper_pickaxe', 'create_sa:experience_pickaxe', 'create_sa:rose_quartz_pickaxe', 'create_sa:zinc_pickaxe'])
  event.add('minecraft:swords', ['create_sa:blazing_cleaver', 'create_sa:brass_sword', 'create_sa:copper_sword', 'create_sa:experience_sword', 'create_sa:rose_quartz_sword', 'create_sa:zinc_sword'])
  event.add('another_furniture:furniture_hammers', ['etcetera:hammer'])
  event.add('forge:tools', ['another_furniture:furniture_hammer', 'etcetera:hammer'])
  event.add('forge:tools/hammer', ['another_furniture:furniture_hammer', 'etcetera:hammer'])
  event.add('forge:tools/hammers', ['another_furniture:furniture_hammer', 'etcetera:hammer'])
})

// INGOTS AND MATERIALS
ServerEvents.tags('item', event => {
  event.add('forge:raw_materials', ['etcetera:raw_bismuth', 'spelunkery:raw_magnetite'])
  event.add('forge:raw_materials/iron', ['spelunkery:raw_magnetite'])
  event.add('forge:raw_materials/bismuth', ['etcetera:raw_bismuth'])
  event.add('forge:storage_blocks', ['etcetera:raw_bismuth_block', 'spelunkery:raw_magnetite_block'])
  event.add('forge:storage_blocks/raw_iron', ['spelunkery:raw_magnetite_block'])
  event.add('forge:storage_blocks/raw_bismuth', ['etcetera:raw_bismuth_block'])
  event.add('forge:ingots', ['spelunkery:raw_magnetite_block'])
  event.add('forge:ingots/bismuth', ['spelunkery:raw_magnetite_block'])
  event.add('forge:gems', ['rubinated_nether:ruby'])
  event.add('forge:bowls', ['tofucraft:glassbowl'])
  event.add('forge:bamboo', ['minecraft:bamboo'])
})

// 调味品
ServerEvents.tags('item', event => {
  event.add('c:salt', ['meadow:alpine_salt', 'spelunkery:salt', 'tofucraft:salt', 'vintagedelight:salt_dust'])
  event.add('c:salts', ['meadow:alpine_salt', 'spelunkery:salt', 'tofucraft:salt', 'vintagedelight:salt_dust'])
  event.add('c:salt_dust', ['meadow:alpine_salt', 'spelunkery:salt', 'tofucraft:salt', 'vintagedelight:salt_dust'])
  event.add('forge:salt', ['meadow:alpine_salt', 'spelunkery:salt', 'tofucraft:salt', 'vintagedelight:salt_dust'])
  event.add('forge:salts', ['meadow:alpine_salt', 'spelunkery:salt', 'tofucraft:salt', 'vintagedelight:salt_dust'])
  event.add('meadow:salt', ['meadow:alpine_salt', 'spelunkery:salt', 'vintagedelight:salt_dust'])
  event.add('forge:bottles/soy_sauce', ['tofucraft:bottle_soysause', 'youkaishomecoming:soy_sauce_bottle'])
  event.add('forge:soysauce', ['youkaishomecoming:soy_sauce_bottle'])
  event.add('forge:soysauce/soysauce', ['youkaishomecoming:soy_sauce_bottle'])
  event.add('forge:hot_spice', ['barbequesdelight:chili_powder'])
})

// 黄油与奶酪
ServerEvents.tags('item', event => {
  event.add('forge:butter', ['bakeries:butter_cube', 'youkaishomecoming:butter'])
  event.add('c:butter', ['bakeries:butter_cube', 'youkaishomecoming:butter'])
  event.add('farm_and_charm:butter', ['bakeries:butter_cube', 'youkaishomecoming:butter'])
  event.add('forge:cheese', ['bakeries:cheese_cube', 'natures_spirit:cheese_bucket', 'netherexp:glowcheese', 'trailandtales_delight:cheese_slice', 'trailandtales_delight:cherry_cheese_slice', 'tofucraft:soy_cheese', 'tofucraft:soy_nether_cheese', 'tofucraft:soy_soul_cheese'])
  event.add('forge:cheese/sweet', ['#forge:cheese'])
  event.add('cornexpansion:cheese', ['bakeries:cheese_cube', 'natures_spirit:cheese_bucket', 'netherexp:glowcheese', 'trailandtales_delight:cheese_slice'])
  event.add('forge:sugar', ['bakeries:brown_sugar_cube'])
})

// 蛋糕
ServerEvents.tags('item', event => {
  event.add('forge:cake', ['atmospheric:yucca_gateau', 'minecraft:cake', 'neapolitan:adzuki_cake', 'neapolitan:banana_cake', 'neapolitan:chocolate_cake', 'neapolitan:mint_cake', 'neapolitan:strawberry_cake', 'neapolitan:vanilla_cake', 'tofucraft:tofucake', 'tofucraft:zundatofucake'])
})

// SLICES
ServerEvents.tags('item', event => {
  event.add('forge:bread_slices', ['bakeries:country_bread_slice', 'bakeries:sliced_cheese_cocoa_toast', 'bakeries:sliced_toast', 'immortalers_delight:kwat_wheat_toast_slice'])
  event.add('forge:bread_slices/wheat', ['bakeries:country_bread_slice', 'bakeries:sliced_cheese_cocoa_toast', 'bakeries:sliced_toast', 'immortalers_delight:kwat_wheat_toast_slice'])
  event.add('some_assembly_required:sandwich_bread', ['bakeries:country_bread_slice', 'bakeries:sliced_cheese_cocoa_toast', 'bakeries:sliced_toast', 'immortalers_delight:kwat_wheat_toast_slice'])
  event.add('forge:bread', ['autumnity:pumpkin_bread', 'bakeries:cheese_cocoa_toast', 'bakeries:ciabatta', 'bakeries:country_bread', 'bakeries:toast', 'immortalers_delight:kwat_wheat_toast', 'neapolitan:banana_bread'])
})

// 法术材料
ServerEvents.tags('item', event => {
  event.add('irons_spellbooks:evocation_focus', ['biomemakeover:illunite_shard', 'netherexp:banshee_rod'])
  event.add('irons_spellbooks:ice_focus', ['biomemakeover:soul_embers'])
  event.add('irons_spellbooks:nature_focus', ['tofucraft:zundaruby'])
  event.add('irons_spellbooks:fire_focus', ['rubinated_nether:molten_ruby'])
  event.add('irons_spellbooks:school_focus', ['biomemakeover:illunite_shard', 'biomemakeover:soul_embers', 'netherexp:banshee_rod', 'rubinated_nether:molten_ruby', 'tofucraft:zundaruby'])
})

// OTHERS
ServerEvents.tags('item', event => {
  event.add('another_furniture:furniture_hammers', ['handcrafted:hammer'])
  event.add('forge:tools', ['handcrafted:hammer'])
  event.add('forge:tools/hammer', ['handcrafted:hammer'])
  event.add('forge:tools/hammers', ['handcrafted:hammer'])
  event.add('forge:seeds/chilipepper', ['crockpot:pepper_seeds'])
})

// UNIFY
ServerEvents.tags('item', event => {
  event.add('pizzacraft:ingredients/sauces/hot_sauce_layer', ['vintagedelight:pepper_jam_bottle', 'vintagedelight:pepper_jam_jar', 'vintagedelight:pepper_jam_mason_jar'])
  event.add('forge:tools/pickaxes', ['#minecraft:pickaxes'])
  event.add('forge:tools/axes', ['#minecraft:axes'])
  event.add('forge:tools/shovels', ['#minecraft:shovels'])
  event.add('forge:tools/swords', ['#minecraft:swords'])
  event.add('forge:tools/hoes', ['#minecraft:hoes'])
  event.add('forge:tools', ['#minecraft:tools'])
  event.add('minecraft:flowers/azalea', ['biomemakeover:buttonbush'])
  event.add('forge:seeds/coffeebean', ['bakeries:raw_coffee_bean', 'youkaishomecoming:green_coffee_bean'])
  event.add('forge:coffee_beans', ['bakeries:coffee_bean', 'youkaishomecoming:coffee_beans'])
  event.add('forge:coffee_powder', ['bakeries:ground_coffee', 'youkaishomecoming:coffee_powder'])
  event.add('minecraft:logs', ['#bloomingnature:logs'])
  event.add('bloomingnature:logs', ['#minecraft:logs'])
  event.add('minecraft:completes_find_tree_tutorial', ['#minecraft:logs'])
  event.add('minecraft:logs_that_burn', ['#bloomingnature:logs'])
  event.add('forge:fruits', ['#forge:berries'])
  event.add('minecraft:fox_food', ['#forge:berries'])
  event.add('c:raw_beef', ['#forge:raw_beef'])
  event.add('farm_and_charm:raw_beef', ['#forge:raw_beef'])
  event.add('farm_and_charm:cooked_beef', ['#forge:cooked_beef'])
  event.add('farmersdelight:cabbage_roll_ingredients', ['#forge:raw_fishes', '#forge:raw_meats'])
  event.add('c:raw_meat', ['#forge:raw_meats'])
  event.add('c:cooked_meat', ['#forge:cooked_meats'])
  event.add('forge:meats', ['#forge:cooked_meats', '#forge:raw_meats'])
  event.add('minecraft:is_meat', ['#forge:meats'])
  event.add('c:raw_fish', ['#forge:raw_fishes'])
  event.add('c:cooked_fish', ['#forge:cooked_fishes'])
  event.add('vinery:grape', ['#forge:crops/grape'])
  event.add('forge:fermentation', ['#forge:crops/grape'])
  event.add('forge:crops/cantaloupe', ['#forge:crops/hamimelon'])
  event.add('forge:crops/hamimelon', ['#forge:crops/cantaloupe'])
  event.add('forge:fruits/cantaloupe', ['#forge:fruits/hamimelon'])
  event.add('forge:fruits/hamimelon', ['#forge:fruits/cantaloupe'])
  event.add('barbequesdelight:raw_skewers', ['#forge:crops/corn', 'casualness_delight:gluten_skewer', 'delightful:marshmallow_stick', 'youkaishomecoming:raw_lamprey'])
  event.add('barbequesdelight:grilled_skewers', ['casualness_delight:roast_gluten', 'delightful:cooked_marshmallow_stick', 'ends_delight:end_barbecue_stick', 'farmersdelight:barbecue_stick', 'mynethersdelight:spicy_skewer', 'youkaishomecoming:roasted_lamprey'])
  event.add('forge:wheat', ['#forge:crops/wheat', '#forge:grain/wheat'])
  event.add('forge:crops/wheat', ['#forge:wheat'])
  event.add('forge:grain/wheat', ['#forge:wheat'])
  event.add('forge:food/raw_pasta', ['farm_and_charm:raw_pasta', 'farmersdelight:raw_pasta', 'vintagedelight:cucumber_noodles'])
  event.add('the_bumblezone:crystalline_flower/cannot_consume', ['#forge:glass_panes', '#forge:ice_cubes', '#forge:nuggets', '#minecraft:slabs', '#spelunkery:nuggets', '#spelunkery:pebbles', 'cuisinedelight:plate', 'irons_spellbooks:blood_vial', 'minecraft:ice'])
  event.add('supplementaries:shulker_blacklist', ['#create:toolboxes', '#curios:spellbook', '#functionalstorage:drawer', '#l2backpack:backpacks', '#l2backpack:bags', '#l2backpack:dimensional_storages', '#l2backpack:drawers', '#l2backpack:swaps', 'caverns_and_chasms:tether_potion', 'cuisinedelight:cuisine_skillet', 'cuisinedelight:fried_meat_and_melon', 'cuisinedelight:fried_mushroom', 'cuisinedelight:fried_pasta', 'cuisinedelight:fried_rice', 'cuisinedelight:ham_fried_rice', 'cuisinedelight:meat_fried_rice', 'cuisinedelight:meat_pasta', 'cuisinedelight:meat_platter', 'cuisinedelight:meat_with_seafood', 'cuisinedelight:meat_with_vegetables', 'cuisinedelight:mixed_fried_rice', 'cuisinedelight:mixed_pasta', 'cuisinedelight:scrambled_egg_and_tomato', 'cuisinedelight:seafood_fried_rice', 'cuisinedelight:seafood_pasta', 'cuisinedelight:seafood_platter', 'cuisinedelight:seafood_with_vegetables', 'cuisinedelight:suspicious_mix', 'cuisinedelight:vegetable_fried_rice', 'cuisinedelight:vegetable_pasta', 'cuisinedelight:vegetable_platter', 'minecraft:bundle', 'minecraft:ender_chest', 'some_assembly_required:sandwich', 'the_bumblezone:crystalline_flower'])
  event.add('touhou_little_maid:maid_tamed_item', ['#forge:cake'])
  event.add('forge:cheeses', ['#forge:cheese'])
  event.add('forge:ice_cubes', ['youkaishomecoming:ice_cube'])
})

// Knives
ServerEvents.tags('item', event => {
  event.add('forge:tools/knives', ['#l2weaponry:dagger'])
  event.add('forge:tools', ['#l2weaponry:dagger'])
  event.add('farmersdelight:tools/knives', ['#l2weaponry:dagger'])
  event.add('farmersdelight:straw_harvesters', ['#l2weaponry:dagger'])
  event.add('immortalers_delight:tools/immortal_knives', ['#forge:tools/knives'])
})

//oei
ServerEvents.tags('item', event => {
  event.add('c:ingots/iron', ['minecraft:iron_ingot'])
  event.add('c:ingots/zinc', ['create:zinc_ingot'])
  event.add('c:stones', ['minecraft:stone'])
  event.add('forge:soybean', ['tofucraft:seeds_soybeans'])
  event.add('forge:redbean', ['neapolitan:adzuki_beans'])
  event.add('forge:strawberry', ['neapolitan:strawberries'])
  event.add('forge:rawchicken', ['minecraft:chicken'])
  event.add('forge:cooked_rice', ['farmersdelight:cooked_rice'])
  event.add('forge:crops/redbean', ['neapolitan:adzuki_beans'])
  event.add('forge:crops/lettuce', ['farm_and_charm:lettuce'])
  event.add('forge:bottles/milk', ['farmersdelight:milk_bottle'])
  event.add('forge:dusts/salt', ['vintagedelight:salt_dust'])
  event.add('sakura:rice/rice', ['farmersdelight:rice'])
  event.add('youkaishomecoming:farmland_redbean', ['minecraft:dirt'])
})

//修补
ServerEvents.tags('block', event => {
  event.add('youkaishomecoming:farmland_redbean', ['minecraft:dirt']) //成就
  event.add('create:tree_attachments', ['netherexp:shroomnight'])
})
